server:
  port: 7001
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1    # tomcat默认大小2M，超过2M的文件不会被捕获，需要调整此处大小为100MB或者-1即可

#
spring:
  profiles:
    active: dev
  banner:
    location: classpath:banner/qiaoba.txt


# 打印日志的级别
logging:
  level:
    root: warn


mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  global-config:
    db-config:
      id-type: assign-id
    banner: false