spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.219:8848
        username: nacos
        password: Chen@0921
    gateway:
      discovery:
        locator:
          enabled: true       # 开启动态路由，从注册中心根据微服务名称获得目标节点
      routes:
        - id: userRoute
          uri: lb://user-service
          predicates:
            - Path=/u/**
        - id: companyRoute
          uri: lb://company-service
          predicates:
            - Path=/c/**