spring:
  redis: #redis的密码和其他密码不一样啊!!
    host: 192.168.31.219
    port: 6379
    database: 0
    password: "092121"
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.219:8848
        username: nacos
        password: Chen@0921
    gateway:
      discovery:
        locator:
          enabled: true       # 开启动态路由，从注册中心根据微服务名称获得目标节点
      routes:
        - id: userRoute
          uri: lb://user-service
          predicates:
            - Path=/u/**,/admininfo/**
        - id: companyRoute
          uri: lb://company-service
          predicates:
            - Path=/c/**
        - id: authRoute
          uri: lb://auth-service
          predicates:
            - Path=/a/**,/passport/**,/saas/**,/admin/**
        - id: resourceRoute
          uri: lb://resource-service
          predicates:
            - Path=/r/**
        - id: workRoute
          uri: lb://work-service
          predicates:
            - Path=/w/**,/resume/**
#      globalcors:           # 配置全局跨域
#        cors-configurations:
#          '[/**]':          # 映射路径
#            allowedOriginPatterns: "*"
#            allowedHeaders: "*"
#            allowedMethods: "*"
#            allowCredentials: true